# .github/workflows/alert-monitor.yml

name: CI/CD for Alert Monitor

on:
  push:
    branches: ["main"]
    paths:
      - "alert_monitor/**"
  workflow_dispatch:

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out application code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r alert_monitor/requirements.txt
          pip install -r requirements-test.txt

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=.
          pytest alert_monitor/

  lint:
    name: Lint Code with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out application code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install and run Ruff
        run: |
          pip install ruff
          ruff check ./alert_monitor

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Check out application code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./alert_monitor
          push: true
          tags: |
            ghcr.io/mordris/alert-monitor:latest
            ghcr.io/mordris/alert-monitor:${{ github.sha }}

  update-config-repo:
    name: Update Kubernetes Manifests
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out config repository
        uses: actions/checkout@v4
        with:
          repository: Mordris/fraud-detection-system-config
          token: ${{ secrets.CONFIG_REPO_PAT }}

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag with Kustomize
        run: |
          cd k8s/overlays/development
          kustomize edit set image placeholder-repo/alert-monitor=ghcr.io/mordris/alert-monitor:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "actions@github.com"
          git commit -am "ci(alert-monitor): Update image to ${{ github.sha }}"
          git push
