# .github/workflows/flink-app.yml

name: CI/CD for Flink App

on:
  push:
    branches: ["main"]
    paths:
      - "flink_app/**"
  workflow_dispatch:

jobs:
  # --- NEW JOB: Lint ---
  # This job runs to check code quality.
  lint:
    name: Lint Code with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out application code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install and run Ruff
        run: |
          pip install ruff
          ruff check ./flink_app

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    # This job can run in parallel with the lint job.
    steps:
      - name: Check out application code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./flink_app
          push: true
          tags: |
            ghcr.io/mordris/flink-app:latest
            ghcr.io/mordris/flink-app:${{ github.sha }}

  update-config-repo:
    name: Update Kubernetes Manifests
    # This job will now ONLY run if BOTH the build and lint jobs succeed.
    needs: [build-and-push, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out config repository
        uses: actions/checkout@v4
        with:
          repository: Mordris/fraud-detection-system-config
          token: ${{ secrets.CONFIG_REPO_PAT }}

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag with Kustomize
        run: |
          cd k8s/overlays/development
          kustomize edit set image placeholder-repo/flink-app=ghcr.io/mordris/flink-app:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "actions@github.com"
          git commit -am "ci(flink-app): Update image to ${{ github.sha }}"
          git push
