# .github/workflows/flink-app.yml

name: CI/CD for Flink App

# This workflow triggers on a push to the main branch,
# but ONLY if changes were made inside the flink_app/ directory.
on:
  push:
    branches: [ "main" ]
    paths:
      - 'flink_app/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out application code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GH_PAT is the secret for your token with 'write:packages' scope
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The context is the directory where the Dockerfile is located
          context: ./flink_app
          push: true
          # Tag the image with 'latest' and the unique Git SHA
          tags: |
            ghcr.io/mordris/flink-app:latest
            ghcr.io/mordris/flink-app:${{ github.sha }}

  update-config-repo:
    name: Update Kubernetes Manifests
    # This job will only run if the 'build-and-push' job succeeds
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Check out config repository
        # Checks out your fraud-detection-system-config repo
        uses: actions/checkout@v4
        with:
          repository: Mordris/fraud-detection-system-config
          # CONFIG_REPO_PAT is the secret for your token with 'repo' scope
          token: ${{ secrets.CONFIG_REPO_PAT }}

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag with Kustomize
        run: |
          # Navigate to the correct overlay
          cd k8s/overlays/development
          # Use kustomize to set the new image. Note the image name must match what's in your kustomization.yaml
          kustomize edit set image ghcr.io/mordris/flink-app=ghcr.io/mordris/flink-app:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "actions@github.com"
          git commit -am "ci(flink-app): Update image to ${{ github.sha }}"
          git push
